SistemaComercial.App.SGC/SGC/Models/Marca/MarcaEditorViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Marca
{
    public class MarcaEditorViewModel
    {
        public MarcaEditorViewModel() { }

        public MarcaEditorViewModel(MarcaResponseDto response)
        {
            Marca = response.Marca;
        }

        public COM_MaeMarca Marca { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Models/Marca/MarcaGridViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Marca
{
    public class MarcaGridViewModel
    {
        public MarcaGridViewModel() { }

        public MarcaGridViewModel(MarcaResponseDto response)
        {
            ListaMarcas = response.ListaMarcas;
        }

        public List<MarcaListaDto> ListaMarcas { get; set; }
        public MarcaFiltroDto Filtro { get; set; }
        public short CodigoMarca { get; set; }
        public string Marca { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Controllers/MarcaController.cs
using SGC.Models.Marca;
using System.Web.Mvc;
using SGC.ServicioSistemaComercial;
using System.Threading.Tasks;
using System.ServiceModel;
using SGC.Helper;
using System.Web.UI.WebControls;

namespace SGC.Controllers
{
    [Atributos.SessionExpireFilter]
    public class MarcaController : Controller
    {
        ServicioSistemaComercialClient _ServicioSistemaComercial = new ServicioSistemaComercialClient();

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        [Atributos.AccesoAutorizadoFilter]
        public async Task<ActionResult> Index(MarcaGridViewModel model)
        {
            try
            {
                //Construimos el modelo
                model = await ObtenerModelGrid(model);

                //Retornamos vista con modelo
                return View(model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        private async Task<MarcaGridViewModel> ObtenerModelGrid(MarcaGridViewModel model)
        {
            model.Filtro = model.Filtro ?? new MarcaFiltroDto();
            //Construimos el request 
            var request = new MarcaRequestDto
            {
                Filtro = model.Filtro
            };

            //Invocamos al servicio
            var response = await _ServicioSistemaComercial.ObtenerIndexMarcaAsync(request);

            //Construimos el modelo
            model = new MarcaGridViewModel(response)
            {
                Filtro = request.Filtro
            };
            //Retornamos el modelo
            return model;

        }

        /// <summary>Método que actualiza la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>16/01/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        public async Task<ActionResult> Refrescar(MarcaGridViewModel model)
        {
            try
            {
                //Construimos el modelo
                model = await ObtenerModelGrid(model);

                //Retornamos vista con modelo
                return PartialView("_Index.Grid", model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        public async Task<ActionResult> Editor(short Id = 0)
        {
            var response = await _ServicioSistemaComercial.ObtenerEditorMarcaAsync(Id);

            //Construimos el modelo
            var model = new MarcaEditorViewModel(response);

            //Retornamos vista con modelo
            return PartialView("_Editor", model);
        }

        /// <summary>Método que graba la Marca</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Vista Refrescar</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpPost]
        public async Task<ActionResult> Agregar(MarcaEditorViewModel model)
        {
            try
            {
                //Construimos el request
                var request = new MarcaRequestDto
                {
                    Marca = model.Marca
                };

                request.Marca.siCodUsuCre = SesionModel.DatosSesion.Usuario.Codigo;

                //Invocamos al servicio
                await _ServicioSistemaComercial.RegistrarMarcaAsync(request);

                //Refrescamos la pagina con los registros actuales
                return RedirectToAction("Refrescar");
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que actualiza la Marca</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Vista Refrescar</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpPost]
        public async Task<ActionResult> Modificar(MarcaEditorViewModel model)
        {
            try
            {
                //Construimos el request
                var request = new MarcaRequestDto
                {
                    Marca = model.Marca
                };

                request.Marca.siCodUsuAct = SesionModel.DatosSesion.Usuario.Codigo;

                //Invocamos al servicio
                await _ServicioSistemaComercial.ActualizarMarcaAsync(request);

                //Refrescamos la pagina con los registros actuales
                return RedirectToAction("Refrescar");
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que elimina la Marca</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Vista Refrescar</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpPost]
        public async Task<ActionResult> Eliminar(int id)
        {
            try
            {
                //Construimos el request
                var request = new MarcaRequestDto
                {
                    Marca = new COM_MaeMarca
                    {
                        iCodMarca = id,
                        siCodUsuAct = 1
                    }
                };

                //Invocamos al servicio
                await _ServicioSistemaComercial.EliminarMarcaAsync(request);

                //Refrescamos la pagina con los registros actuales
                return RedirectToAction("Refrescar");
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que exporta a archivo excel el listado de modo pago garitas</summary>
        /// <param name="model">Modelo del request</param>

SistemaComercial.App.SGC/SGC/Views/Marca/Index.cshtml
@model SGC.Models.Marca.MarcaGridViewModel
@{
    ViewBag.Title = "Marcas";
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Marcas</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20"><i class="ti-settings text-white"></i></button>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
            <li class="active">Marcas</li>
        </ol>
    </div>
</div>

<div class="row">
    @{ Html.RenderPartial("_Index", Model); }
</div>

SistemaComercial.App.SGC/SGC/Views/Marca/_Editor.cshtml
@model SGC.Models.Marca.MarcaEditorViewModel

<form id="marcaEditorForm" enctype="multipart/form-data" method="POST" action="/" class="form-horizontal" autocomplete="off">
    @Html.HiddenFor(model => model.Marca.iCodMarca)

    <div class="form-group">
        <label class="col-sm-3 control-label">Descripción :</label>
        <div class="col-sm-9">
            @Html.TextBoxFor(model => model.Marca.vDescripcion, new { @class = "form-control form-control-line", @placeholder = "Descripción de marca", @required = "required", @maxlength = "50" })
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label">Abreviatura :</label>
        <div class="col-sm-9">
            @Html.TextBoxFor(model => model.Marca.vAbreviatura, new { @class = "form-control form-control-line minu", @placeholder = "Abreviatura de marca", @required = "required", @maxlength = "20" })
        </div>
    </div>

    <br />
</form>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        marca.editor.load();
    });
</script>

SistemaComercial.App.SGC/SGC/Views/Marca/_Index.Grid.cshtml
@using SGC.Helper
@model SGC.Models.Marca.MarcaGridViewModel

@{
    var per = HelperFunciones.ValidaTienePermiso(HelperConstantes.Permisos.PUEDE_CREAREDITAR_MARCA).ToString();
}

<div class="panel-wrapper collapse in" id="marca-wrapper">
    <div class="panel-body table-responsive">
        <table class="table color-table inverse-table table-striped" id="tblLista">
            <thead>
                <tr class="row-head">
                    <th width="40%">DESCRIPCIÓN</th>
                    <th width="20%">ABREVIATURA</th>
                    <th width="15%">USUARIO REGISTRO</th>
                    <th width="25%">ACCIONES</th>
                </tr>
            </thead>

            <tbody id="tbodylst">
                @foreach (var item in Model.ListaMarcas)
                {
                    <tr role="row">
                        <td>
                            <a href="#" onclick="marca.editor.init(@item.Codigo, '@per')">@item.Descripcion</a>
                        </td>
                        <td>@item.Abreviatura</td>
                        <td>@item.UsuarioCrea</td>
                        <td class="text-nowrap" align="center">
                            @HelperHTML.CrearLinkSiTienePermiso(HelperConstantes.Permisos.PUEDE_ELIMINAR_MARCA, "marca.grid.eliminar", item.Codigo.ToString(), "Eliminar", "btn btn-info btn-outline btn-circle btn-sm m-r-5", "ti-trash")
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        marca.grid.paginarParcial();
    });
</script>

SistemaComercial.App.SGC/SGC/Views/Marca/_Index.Head.cshtml
@using SGC.Helper
@model SGC.Models.Marca.MarcaGridViewModel

<div class="panel-heading">
    <div class="row">
        @if (HelperFunciones.ValidaTienePermiso(HelperConstantes.Permisos.PUEDE_CREAREDITAR_MARCA))
        {
            <div class="col-lg-2 col-sm-4 col-xs-2">
                <button type="button" class="btn btn-block btn-outline btn-default btn-agregar waves-effect waves-light">
                    <span class="visible-lg visible-md"><i class="icon-plus m-r-5 fa-1.5x"></i>Nuevo</span>
                    <span class="visible-xs visible-sm"><i class="icon-plus m-r-5 fa-1.5x"></i></span>
                </button>
            </div>
        }
        <div class="col-lg-2 col-sm-4 col-xs-2">
            <button type="button" class="btn btn-block btn-outline btn-default btn-exportar waves-effect waves-light">
                <span class="visible-lg visible-md"><i class="fa fa-file-excel-o m-r-5 fa-1.5x"></i>Exportar</span>
                <span class="visible-xs visible-sm"><i class="fa fa-file-excel-o m-r-5 fa-1.5x"></i></span>
            </button>
        </div>

        <div class="col-lg-2 col-sm-4 col-xs-2 pull-right">
            <div class="panel-action">
                <a href="#" data-perform="panel-collapse">
                    <i class="ti-plus"></i>
                </a>
            </div>
        </div>

    </div>
</div>

<div class="panel-wrapper collapse" aria-expanded="false">
    <div class="panel-body">
        @Html.Hidden("hdnURLExportar", Url.Action("Exportar", "Marca", null))
        <div class="form-group">

            <div class="col-md-6">
                <label class="col-md-12">Marca</label>
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.Filtro.Descripcion, new { @class = "form-control form-control-line", @maxlength = "50", @placeholder = "Buscar por nombre de marca..." })
                </div>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-2">
                <button type="button" class="btn btn-block btn-outline btn-default btn-search  waves-effect waves-light">
                    <span class="visible-lg visible-md"><i class="fa fa-search m-r-5 fa-1.5x"></i>Buscar</span>
                    <span class="visible-xs visible-sm"><i class="fa fa-search m-r-5 fa-1.5x"></i></span>
                </button>
            </div>
        </div>
    </div>
</div>

SistemaComercial.App.SGC/SGC/Views/Marca/_Index.cshtml
@model SGC.Models.Marca.MarcaGridViewModel

<div class="col-sm-12">
    <form id="marcaGridForm" action="/" class="form-horizontal" autocomplete="off">
        <div class="panel panel-default">
            @{ Html.RenderPartial("_Index.Head", Model); }
        </div>
    </form>
</div>

<div class="col-sm-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Lista de Marcas
        </div>
        @{ Html.RenderPartial("_Index.Grid", Model); }
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        marca.grid.load();
    });
</script>