SistemaComercial.App.SGC/SGC/Models/Archivo/ArchivosGridViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;
using System.Web;

namespace SGC.Models.Archivo
{
    public class ArchivosGridViewModel
    {
        public ArchivosGridViewModel() { }

        public ArchivosGridViewModel(ArchivosResponseDto response)
        {
            ListaArchivos = response.ListaArchivos;
        }

        public List<ArchivoListaDto> ListaArchivos { get; set; }
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public HttpPostedFileBase Archivo { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Models/Movimiento/MovimientoDeclaracionJuradaViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;
using System;
using System.Data;

namespace SGC.Models.Movimiento
{
    public class MovimientoDeclaracionJuradaViewModel
    {

        public static DataTable DTReporteDeclaracion(MovimientoResponseDto response)
        {
            DataTable dt = new DataTable("tbDetalleDeclaracion");
            dt.Columns.Add("DAM", typeof(string));
            dt.Columns.Add("Serie", typeof(string));
            dt.Columns.Add("Cantidad", typeof(string));
            dt.Columns.Add("Codigo", typeof(string));
            dt.Columns.Add("Descripcion", typeof(string));
            dt.Columns.Add("ValorFOB", typeof(string));
            dt.Columns.Add("ValorUSD", typeof(string));

            var cont = 0;
            foreach (var item in response.ListaMovimientoDetalle)
            {
                dt.Rows.Add("", item.Serie, 1, item.Codigo, item.NombreProducto, item.CostoIngreso, item.CostoIngreso);
                cont++;
            }

            return dt;
        }
    }


}

SistemaComercial.App.SGC/SGC/Models/Movimiento/MovimientoDetalleViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Movimiento
{
    public class MovimientoDetalleViewModel
    {
        public MovimientoDetalleViewModel() { }

        public MovimientoDetalleViewModel(MovimientoResponseDto response)
        {
            Movimiento = response.MovimientoCabecera;
            MovimientoDetalle = response.MovimientoDetalle;
            Stock = response.Stock;
            DetalleStock = response.DetalleStock ?? new COM_DetStock();
            MovimientoDetalleDto = response.MovimientoDetalleDto ?? new DetalleMovimientoListaDto();
            MovimientoDetalle = response.MovimientoDetalle ?? new COM_DetMovArt();

            LstAlmacenes = new List<SelectListItem>();
            LstEstadosArticulos = new List<SelectListItem>();
            LstPisos = new List<SelectListItem>();
            LstRacks = new List<SelectListItem>();
            LstUbicaciones = new List<SelectListItem>();
            Piso = response.Piso;
            Rack = response.Rack;

            if (response.ListaAlmacenes != null) foreach (GenericoListaDto item in response.ListaAlmacenes) LstAlmacenes.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaEstadosArticulo != null) foreach (GenericoListaDto item in response.ListaEstadosArticulo) LstEstadosArticulos.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaPisos != null) foreach (GenericoListaDto item in response.ListaPisos) LstPisos.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaRacks != null) foreach (GenericoListaDto item in response.ListaRacks) LstRacks.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaUbicaciones != null) foreach (GenericoListaDto item in response.ListaUbicaciones) LstUbicaciones.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });

        }

        public COM_TabStock Stock { get; set; }
        public COM_DetStock DetalleStock { get; set; }
        public COM_CabMovArt Movimiento { get; set; }
        public COM_DetMovArt MovimientoDetalle { get; set; }
        public DetalleMovimientoListaDto MovimientoDetalleDto { get; set; }
        public List<SelectListItem> LstAlmacenes { get; set; }
        public List<SelectListItem> LstEstadosArticulos { get; set; }
        public List<SelectListItem> LstPisos { get; set; }
        public List<SelectListItem> LstRacks { get; set; }
        public List<SelectListItem> LstUbicaciones { get; set; }
        public string Piso { get; set; }
        public string Rack { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Models/Movimiento/MovimientoGridViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Movimiento
{
    public class MovimientoGridViewModel
    {
        public MovimientoGridViewModel() { }

        public MovimientoGridViewModel(MovimientoResponseDto response)
        {
            ListaMovimientos = response.ListaMovimientos;

            LstTiposMov = new List<SelectListItem>();
            LstTiposDoc = new List<SelectListItem>();
            LstUsuarios = new List<SelectListItem>();

            if (response.ListaTiposMov != null) foreach (GenericoListaDto item in response.ListaTiposMov) LstTiposMov.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaTiposDoc != null) foreach (GenericoListaDto item in response.ListaTiposDoc) LstTiposDoc.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaUsuarios != null) foreach (GenericoListaDto item in response.ListaUsuarios) LstUsuarios.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
        }

        public MovimientoFiltroDto Filtro { get; set; }
        public List<MovimientoListaDto> ListaMovimientos { get; set; }
        public List<SelectListItem> LstTiposMov { get; set; }
        public List<SelectListItem> LstTiposDoc { get; set; }
        public List<SelectListItem> LstUsuarios { get; set; }
        public string ParamEditor { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Models/Movimiento/MovimientoLiquidacionViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Movimiento
{
    public class MovimientoLiquidacionViewModel
    {
        public MovimientoLiquidacionViewModel() { }

        public MovimientoLiquidacionViewModel(MovimientoLiquidacionResponseDto response)
        {
            Liquidacion = response.Liquidacion ?? new COM_Liquidacion();
        }

        public COM_Liquidacion Liquidacion { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Controllers/ArchivosController.cs
using SGC.Models.Movimiento;
using System.Web.Mvc;
using SGC.ServicioSistemaComercial;
using System.Threading.Tasks;
using System.ServiceModel;
using SGC.Helper;
using System.Web.UI.WebControls;
using SistemaComercial.App.Utility;
using System.Web.Routing;
using System.Data;
//using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using SGC.Models.Archivo;
using System;
namespace SGC.Controllers
{
    [Atributos.SessionExpireFilter]
    public class ArchivosController : Controller
    {
        ServicioSistemaComercialClient _ServicioSistemaComercial = new ServicioSistemaComercialClient();

        [HttpGet]
        public async Task<FileResult> Descargar(string id)
        {
            var response = await _ServicioSistemaComercial.ObtenerArchivoPorIdAsync(id);

            return File(response.Archivo.Archivo, response.Archivo.Extension, response.Archivo.Nombre);
        }
    }
}

SistemaComercial.App.SGC/SGC/Controllers/MovimientoController.cs
using SGC.Models.Movimiento;
using System.Web.Mvc;
using SGC.ServicioSistemaComercial;
using System.Threading.Tasks;
using System.ServiceModel;
using SGC.Helper;
using System.Web.UI.WebControls;
using SistemaComercial.App.Utility;
using System.Web.Routing;
using System.Data;
using System.IO;
using SGC.Models.Archivo;
using System;
using SGC.Models.Articulo;
using CrystalDecisions.CrystalReports.Engine;
using System.Collections.Generic;
using CrystalDecisions.Shared;

namespace SGC.Controllers
{
    [Atributos.SessionExpireFilter]
    public class MovimientoController : Controller
    {
        ServicioSistemaComercialClient _ServicioSistemaComercial = new ServicioSistemaComercialClient();

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        [Atributos.AccesoAutorizadoFilter]
        public async Task<ActionResult> Ingresos(MovimientoGridViewModel model)
        {
            try
            {
                //Construimos el modelo
                var tipoMov = System.Convert.ToByte(Constantes.Tablas.TipoMovimiento.INGRESO);
                model = await ObtenerModelGrid(model, tipoMov);

                //Retornamos vista con modelo
                return View(model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        [Atributos.AccesoAutorizadoFilter]
        public async Task<ActionResult> Salidas(MovimientoGridViewModel model)
        {
            try
            {
                //Construimos el modelo
                var tipoMov = System.Convert.ToByte(Constantes.Tablas.TipoMovimiento.SALIDA);
                model = await ObtenerModelGrid(model, tipoMov);

                //Retornamos vista con modelo
                return View(model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        private async Task<MovimientoGridViewModel> ObtenerModelGrid(MovimientoGridViewModel model, byte tipo)
        {
            model.Filtro = model.Filtro ?? new MovimientoFiltroDto();
            //Construimos el request 
            var request = new MovimientoRequestDto
            {
                Filtro = model.Filtro
            };

            request.Filtro.TipoMovimiento = tipo;

            //Invocamos al servicio
            var response = await _ServicioSistemaComercial.ObtenerIndexMovimientosAsync(request);

            //Construimos el modelo
            model = new MovimientoGridViewModel(response)
            {
                Filtro = request.Filtro
            };
            //Retornamos el modelo
            return model;

        }

        /// <summary>Método que actualiza la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>16/01/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        public async Task<ActionResult> Refrescar(MovimientoGridViewModel model)
        {
            try
            {
                //Construimos el modelo
                model = await ObtenerModelGrid(model, 1);

                //Retornamos vista con modelo
                return PartialView("_Index.Grid", model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpPost]
        public ActionResult RedirectEditor(string Id)
        {
            SesionModel.FiltrosMovimiento = new MovimientoGridViewModel
            {
                ParamEditor = Id
            };

            var host = GeneralController.RutaRaiz(Request);
            var ruta = host + "Movimiento/Editor";
            return Json(ruta);
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        public async Task<ActionResult> Editor()
        {
            var paramEditor = SesionModel.FiltrosMovimiento.ParamEditor;
            if (paramEditor == null)
            {
                return RedirectToAction("Ingresos");
            }
            SesionModel.FiltrosMovimiento = null;

            var id = Funciones.Check.Int32(paramEditor.Split('|')[0]);
            var tipo = Funciones.Check.Int32(paramEditor.Split('|')[1]);
            var form = Funciones.Check.Cadena(paramEditor.Split('|')[2]);
            string vista;

            var response = await _ServicioSistemaComercial.ObtenerEditorMovimientoAsync(id);
            var tipoMovIngreso = System.Convert.ToByte(Constantes.Tablas.TipoMovimiento.INGRESO);
            var tipoMovSalida = System.Convert.ToByte(Constantes.Tablas.TipoMovimiento.SALIDA);
            vista = string.Empty;

            //Construimos el modelo
            var model = new MovimientoEditorViewModel(response, form);

            if (tipo == 0)
            {
                switch (model.Movimiento.vTipoMov)
                {
                    case "IMP":
                        vista = "Ingresos._EditorImportacion";
                        break;
                    case "DEV":
                        vista = "Ingresos._EditorDevolucion";
                        break;
                    case "COM":
                        vista = "Ingresos._EditorCompra";
                        break;
                    case "EXP":
                        vista = "Salidas._EditorExportacion";
                        break;
                    case "DEL":
                        vista = "Salidas._EditorDelivery";
                        break;
                    case "VEN":
                        vista = "Salidas._EditorVentas";
                        break;
                    default:
                        break;
                }
            }
            else
            {
                if (tipo == 1)
                {
                    model.Movimiento.tiCodTipMov = tipoMovIngreso;
                }
                else
                {
                    model.Movimiento.tiCodTipMov = tipoMovSalida;
                }
                switch (form)
                {
                    case "IMP":

SistemaComercial.App.SGC/SGC/Views/Movimiento/Ingresos._EditorDevolucion.cshtml
@using SistemaComercial.App.Utility
@using SGC.Helper
@model SGC.Models.Movimiento.MovimientoEditorViewModel

@{
    ViewBag.Title = "Movimientos";
    var per = HelperFunciones.ValidaTienePermiso(HelperConstantes.Permisos.PUEDE_CREAREDITAR_MOVIMIENTO).ToString();
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Recolección de productos</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20"><i class="ti-settings text-white"></i></button>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
            <li class="active">Devolución de productos</li>
        </ol>
    </div>
</div>

<form id="movimientoEditorForm" enctype="multipart/form-data" method="POST" action="/" class="form-horizontal" autocomplete="off">

    <div class="row">

        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    @if (!Model.Movimiento.bCerrado && HelperFunciones.ValidaTienePermiso(HelperConstantes.Permisos.PUEDE_CREAREDITAR_MOVIMIENTO))
                    {
                        <div class="col-lg-2 col-sm-4 col-xs-2">
                            <button type="button" class="btn btn-block btn-outline btn-default btn-agregar waves-effect waves-light">
                                <span class="visible-lg visible-md"><i class="ti-save m-r-5 fa-1.5x"></i>Guardar</span>
                                <span class="visible-xs visible-sm"><i class="ti-save m-r-5 fa-1.5x"></i></span>
                            </button>
                        </div>

                        if (Model.Movimiento.iCodCabMov > 0)
                        {
                            <div class="col-lg-2 col-sm-4 col-xs-2">
                                <a href="javascript:void(0)" class="btn btn-block btn-outline btn-default btn-cerrar  waves-effect waves-light">
                                    <span class="visible-lg visible-md"><i class="icon-action-undo m-r-5 fa-1.5x"></i>Cerrar</span>
                                    <span class="visible-xs visible-sm"><i class="icon-action-undo m-r-5 fa-1.5x"></i></span>
                                </a>
                            </div>
                        }
                        else
                        {
                            <div class="col-lg-2 col-sm-4 col-xs-2 div-cerrar" style="display:none">
                                <a href="javascript:void(0)" class="btn btn-block btn-outline btn-default btn-cerrar  waves-effect waves-light">
                                    <span class="visible-lg visible-md"><i class="icon-action-undo m-r-5 fa-1.5x"></i>Cerrar</span>
                                    <span class="visible-xs visible-sm"><i class="icon-action-undo m-r-5 fa-1.5x"></i></span>
                                </a>
                            </div>
                        }

                    }
                    else
                    {
                        if (Model.Movimiento.bCerrado)
                        {
                            <div class="col-lg-2 col-sm-4 col-xs-2">
                                <span class="counter text-info">CERRADO</span>
                            </div>
                        }
                    }
                    <div class="col-lg-2 col-sm-4 col-xs-2">
                        <button type="button" class="btn btn-block btn-outline btn-default btn-adjunto waves-effect waves-light">
                            <span class="visible-lg visible-md"><i class="ti-save m-r-5 fa-1.5x"></i>Agregar archivos</span>
                            <span class="visible-xs visible-sm"><i class="ti-save m-r-5 fa-1.5x"></i></span>
                        </button>
                    </div>
                    <div class="col-lg-2 col-sm-4 col-xs-2">
                        <a href="@Url.Action("Ingresos","Movimiento")" class="btn btn-block btn-outline btn-default btn-volver  waves-effect waves-light">
                            <span class="visible-lg visible-md"><i class="icon-action-undo m-r-5 fa-1.5x"></i>Volver</span>
                            <span class="visible-xs visible-sm"><i class="icon-action-undo m-r-5 fa-1.5x"></i></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="white-box">
            <!-- Nav tabs -->
            <ul class="nav customtab nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#home1" aria-controls="home" role="tab" data-toggle="tab" aria-expanded="true"><span class="visible-xs"><i class="ti-home"></i></span><span class="hidden-xs"> Datos Devolución</span></a></li>
                <li role="presentation" class=""><a href="#settings1" aria-controls="settings" role="tab" data-toggle="tab" aria-expanded="false"><span class="visible-xs"><i class="ti-settings"></i></span> <span class="hidden-xs">Productos</span></a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade active in" id="home1">
                    <div class="panel-body">

                        @Html.HiddenFor(model => model.Movimiento.iCodCabMov)
                        @Html.HiddenFor(model => model.Movimiento.tiCodTipMov)
                        <input type="hidden" value="DEV" id="Movimiento_vTipoMov" name="Movimiento.vTipoMov" />
                        <input type="hidden" value="0" id="hdnNuevoArt" />
                        <input type="hidden" value="@per" id="hdnPerm" />
                        <input type="hidden" value="@Constantes.Tablas.TipoDocIdentidad.RUC" id="hdnTipDocIde" />

                        <div class="form-group">

                            <div class="col-md-4">
                                <label class="col-md-12">FECHA MOVIMIENTO</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-clock-o"></i>
                                    </div>
                                    @Html.TextBoxFor(model => model.MovimientoDto.FechaRecepcion, new { @class = "form-control pull-right  form-control-line" })
                                </div>
                            </div>
                            <div class="col-md-4">
                                <label class="col-md-12">HORA MOVIMIENTO</label>
                                <div class="input-group clockpicker " data-placement="bottom" data-align="top" data-autoclose="true">
                                    <span class="input-group-addon"> <span class="glyphicon glyphicon-time"></span> </span>
                                    @Html.TextBoxFor(model => model.MovimientoDto.HoraRecepcion, new { @class = "form-control pull-right  form-control-line" })
                                </div>
                            </div>

                            <div class="col-md-4">
                                <label class="col-md-12">CORRELATIVO</label>
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.Movimiento.vCorrelativo, new { @class = "form-control", @readonly = "readonly" })
                                </div>
                            </div>

                        </div>

                        <div class="form-group">

                            <div class="col-md-4">
                                <label class="col-md-12">GUIA</label>
                                <div class="col-sm-12">
                                    @Html.TextBoxFor(model => model.Movimiento.vNumeroDoc, new { @class = "form-control form-control-line", @placeholder = "Número", @align = "right", @maxlength = "20" })
                                </div>
                            </div>

                            <div class="col-md-4">
                                <label class="col-md-12">ETA</label>
                                <div class="col-sm-12">
                                    <input type="text" name="MovimientoExt.sdFechaETA" id="MovimientoExt_sdFechaETA" value="@Model.MovimientoExt.sdFechaETA" data-mask="99/99/9999 99:99" class="form-control form-control-line" maxlength="16"/>
                                </div>
                            </div>

                            @*<div class="col-md-4">
            <label class="col-md-12">ETA</label>
            <div class="input-group date">
                <div class="input-group-addon">
                    <i class="fa fa-clock-o"></i>
                </div>
                @Html.TextBoxFor(model => model.MovimientoExt.sdFechaETA, new { @class = "form-control pull-right  form-control-line" })

                
            </div>
        </div>*@

                            <div class="col-md-4">
                                <label class="col-md-12">RMA</label>
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.MovimientoExt.vRMA, new { @class = "form-control form-control-line", @placeholder = "RMA", @maxlength = "30" })
                                </div>
                            </div>

                        </div>

                        <div class="form-group">

                            <div class="col-md-6">
                                <label class="col-md-12">PARTNER</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(model => model.MovimientoExt.iCodPartner, Model.LstEmpresasPartner, "--Seleccione--", new { @class = "form-control form-control-line select2", @required = "required" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label class="col-md-12">CLIENTE</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(model => model.Movimiento.iCodPer, Model.LstEmpresas, "--Seleccione--", new { @class = "form-control form-control-line select2", @required = "required" })
                                </div>
                            </div>

                        </div>

                        <div class="form-group ext">
                            <div class="col-md-12">
                                <label class="col-md-12">OBSERVACIÓN</label>
                                <div class="col-md-12">
                                    @Html.TextAreaFor(model => model.Movimiento.vObservacion, new { @class = "form-control form-control-line", @placeholder = "Ingrese alguna observación", @maxlength = "150" })
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div role="tabpanel" class="tab-pane fade" id="settings1">
                    @{ Html.RenderPartial("_Editor.Grid", Model); }
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>

    </div>

</form>


<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        movimiento.editor.load();
    });
</script>

SistemaComercial.App.SGC/SGC/Views/Movimiento/Salidas.cshtml
@model SGC.Models.Movimiento.MovimientoGridViewModel
@{
    ViewBag.Title = "Salida de Productos";
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Salida de productos</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20"><i class="ti-settings text-white"></i></button>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
            <li class="active">Salida de productos</li>
        </ol>
    </div>
</div>

<div class="row">
    @{ Html.RenderPartial("Salidas._Index", Model); }
</div>