SistemaComercial.App.SGC/SGC/Models/Persona/PersonaContactoEditorViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Persona
{
    public class PersonaContactoEditorViewModel
    {
        public PersonaContactoEditorViewModel() { }

        public PersonaContactoEditorViewModel(PersonaResponseDto response)
        {
            Contacto = response.ContactoPersona ?? new COM_TabPersona_Contacto();
        }

        public COM_TabPersona_Contacto Contacto { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Models/Persona/PersonaEditorViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Persona
{
    public class PersonaEditorViewModel
    {
        public PersonaEditorViewModel() { }

        public PersonaEditorViewModel(PersonaResponseDto response)
        {
            Persona = response.Persona ?? new COM_TabPersona();
            ListaContactos = response.ListaContactos;
            ListaOficinas = response.ListaOficinas;

            LstPaises = new List<SelectListItem>();
            LstTipDocIdentidad = new List<SelectListItem>();

            if (response.ListaPaises != null) foreach (GenericoListaDto item in response.ListaPaises) LstPaises.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaTipDocIdentidad != null) foreach (GenericoListaDto item in response.ListaTipDocIdentidad) LstTipDocIdentidad.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
        }

        public COM_TabPersona Persona { get; set; }
        public List<PersonaContactoListaDto> ListaContactos { get; set; }
        public List<PersonaOficinaListaDto> ListaOficinas { get; set; }
        public List<SelectListItem> LstPaises { get; set; }
        public List<SelectListItem> LstTipDocIdentidad { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Models/Persona/PersonaGridViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Persona
{
    public class PersonaGridViewModel
    {
        public PersonaGridViewModel() { }

        public PersonaGridViewModel(PersonaResponseDto response)
        {
            ListaPersonas = response.ListaPersonas;
        }

        public List<PersonaListaDto> ListaPersonas { get; set; }
        public PersonaFiltroDto Filtro { get; set; }
        public short CodigoUnidadMedida { get; set; }
        public string UnidadMedida { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Models/Persona/PersonaOficinaEditorViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;

namespace SGC.Models.Persona
{
    public class PersonaOficinaEditorViewModel
    {
        public PersonaOficinaEditorViewModel() { }

        public PersonaOficinaEditorViewModel(PersonaResponseDto response)
        {
            Oficina = response.OficinaPersona ?? new COM_TabPersona_Oficina();

            LstPaises = new List<SelectListItem>();

            if (response.ListaPaises != null) foreach (GenericoListaDto item in response.ListaPaises) LstPaises.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
        }

        public COM_TabPersona_Oficina Oficina { get; set; }
        public List<SelectListItem> LstPaises { get; set; }
    }
}

SistemaComercial.App.SGC/SGC/Controllers/PersonaController.cs
using SGC.Models.Persona;
using System.Web.Mvc;
using SGC.ServicioSistemaComercial;
using System.Threading.Tasks;
using System.ServiceModel;
using SGC.Helper;
using System.Web.UI.WebControls;
using System.Web.Routing;

namespace SGC.Controllers
{
    public class PersonaController : Controller
    {
        ServicioSistemaComercialClient _ServicioSistemaComercial = new ServicioSistemaComercialClient();

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        [Atributos.AccesoAutorizadoFilter]
        public async Task<ActionResult> Search(PersonaGridViewModel model)
        {
            try
            {
                //model = SesionModel.FiltrosPersona;
                //SesionModel.FiltrosPersona = null;

                //Construimos el modelo
                model = await ObtenerModelGrid(model);

                //Retornamos vista con modelo
                return View("Index",model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        private async Task<PersonaGridViewModel> ObtenerModelGrid(PersonaGridViewModel model)
        {
            model.Filtro = model.Filtro ?? new PersonaFiltroDto();
            //Construimos el request 
            var request = new PersonaRequestDto
            {
                Filtro = model.Filtro
            };

            //Invocamos al servicio
            var response = await _ServicioSistemaComercial.ObtenerIndexPersonasAsync(request);

            //Construimos el modelo
            model = new PersonaGridViewModel(response)
            {
                Filtro = request.Filtro
            };
            //Retornamos el modelo
            return model;

        }

        /// <summary>Método que actualiza la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>16/01/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        public async Task<ActionResult> Refrescar(PersonaGridViewModel model)
        {
            try
            {
                //Construimos el modelo
                model = await ObtenerModelGrid(model);

                //Retornamos vista con modelo
                return PartialView("_Index.Grid", model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        public async Task<ActionResult> Editor(int Id = 0)
        {
            var response = await _ServicioSistemaComercial.ObtenerEditorPersonaAsync(Id);

            //Construimos el modelo
            var model = new PersonaEditorViewModel(response);

            //Retornamos vista con modelo
            return View("_Editor", model);
        }

        /// <summary>Método que graba la Persona</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Vista Refrescar</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpPost]
        public async Task<ActionResult> Agregar(PersonaEditorViewModel model)
        {
            try
            {
                //Construimos el request
                var request = new PersonaRequestDto
                {
                    Persona = model.Persona
                };

                request.Persona.siCodUsuCre = SesionModel.DatosSesion.Usuario.Codigo;

                //Invocamos al servicio
                var id = await _ServicioSistemaComercial.RegistrarPersonaAsync(request);

                //Refrescamos la pagina con los registros actuales
                return Json(id, JsonRequestBehavior.AllowGet);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que actualiza la Persona</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Vista Refrescar</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpPost]
        public async Task<ActionResult> Modificar(PersonaEditorViewModel model)
        {
            try
            {
                //Construimos el request
                var request = new PersonaRequestDto
                {
                    Persona = model.Persona
                };

                request.Persona.siCodUsuAct = SesionModel.DatosSesion.Usuario.Codigo;

                //Invocamos al servicio
                await _ServicioSistemaComercial.ActualizarPersonaAsync(request);

                //Refrescamos la pagina con los registros actuales
                return Json("1", JsonRequestBehavior.AllowGet);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que elimina la Persona</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Vista Refrescar</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpPost]
        public async Task<ActionResult> Eliminar(int id)
        {
            try
            {
                //Construimos el request
                var request = new PersonaRequestDto
                {
                    Persona = new COM_TabPersona
                    {
                        iCodPer = id,
                        siCodUsuAct = 1
                    }
                };

                //Invocamos al servicio
                await _ServicioSistemaComercial.EliminarPersonaAsync(request);

                //Refrescamos la pagina con los registros actuales
                return RedirectToAction("Refrescar");
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }

SistemaComercial.App.SGC/SGC/Views/Persona/Index.cshtml
@model SGC.Models.Persona.PersonaGridViewModel
@{
    ViewBag.Title = "Empresas/Personas";
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Empresas/Personas</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20"><i class="ti-settings text-white"></i></button>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
            <li class="active">Empresas/Personas</li>
        </ol>
    </div>
</div>

<div class="row">
    @{ Html.RenderPartial("_Index", Model); }
</div>

SistemaComercial.App.SGC/SGC/Views/Persona/_Editor.Contacto.cshtml
@using SGC.Helper
@model SGC.Models.Persona.PersonaEditorViewModel

<div class="panel panel-default">

    <div class="col-sm-12">
        <form id="personaContactoGridForm" action="/" class="form-horizontal" autocomplete="off">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <div class="row">
                        @if (HelperFunciones.ValidaTienePermiso(HelperConstantes.Permisos.PUEDE_CREAREDITAR_EMPRESA))
                        {
                            <div class="col-lg-2 col-sm-4 col-xs-2">
                                <button type="button" class="btn btn-block btn-outline btn-default btn-agregar waves-effect waves-light">
                                    <span class="visible-lg visible-md"><i class="icon-plus m-r-5 fa-1.5x"></i>Nuevo</span>
                                    <span class="visible-xs visible-sm"><i class="icon-plus m-r-5 fa-1.5x"></i></span>
                                </button>
                            </div>
                        }
                        <div class="col-lg-2 col-sm-4 col-xs-2">
                            <button type="button" class="btn btn-block btn-outline btn-default btn-exportar waves-effect waves-light">
                                <span class="visible-lg visible-md"><i class="fa fa-file-excel-o m-r-5 fa-1.5x"></i>Exportar</span>
                                <span class="visible-xs visible-sm"><i class="fa fa-file-excel-o m-r-5 fa-1.5x"></i></span>
                            </button>
                        </div>
                        <div class="col-lg-2 col-sm-4 col-xs-2">
                            <a href="@Url.Action("Index","Persona")" class="btn btn-block btn-outline btn-default btn-volver  waves-effect waves-light">
                                <span class="visible-lg visible-md"><i class="icon-action-undo m-r-5 fa-1.5x"></i>Volver</span>
                                <span class="visible-xs visible-sm"><i class="icon-action-undo m-r-5 fa-1.5x"></i></span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    @{ Html.RenderPartial("_Editor.Contacto.Grid", Model); }
                </div>

            </div>
        </form>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function () {
        personacontacto.grid.load();
    });
</script>

SistemaComercial.App.SGC/SGC/Views/Persona/_Editor.Oficina.cshtml
@using SGC.Helper
@model SGC.Models.Persona.PersonaEditorViewModel

<div class="panel panel-default">

    <div class="col-sm-12">
        <form id="personaOficinaGridForm" action="/" class="form-horizontal" autocomplete="off">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <div class="row">
                        @if (HelperFunciones.ValidaTienePermiso(HelperConstantes.Permisos.PUEDE_CREAREDITAR_EMPRESA))
                        {
                            <div class="col-lg-2 col-sm-4 col-xs-2">
                                <button type="button" class="btn btn-block btn-outline btn-default btn-agregar waves-effect waves-light">
                                    <span class="visible-lg visible-md"><i class="icon-plus m-r-5 fa-1.5x"></i>Nuevo</span>
                                    <span class="visible-xs visible-sm"><i class="icon-plus m-r-5 fa-1.5x"></i></span>
                                </button>
                            </div>
                        }
                        <div class="col-lg-2 col-sm-4 col-xs-2">
                            <button type="button" class="btn btn-block btn-outline btn-default btn-exportar waves-effect waves-light">
                                <span class="visible-lg visible-md"><i class="fa fa-file-excel-o m-r-5 fa-1.5x"></i>Exportar</span>
                                <span class="visible-xs visible-sm"><i class="fa fa-file-excel-o m-r-5 fa-1.5x"></i></span>
                            </button>
                        </div>
                        <div class="col-lg-2 col-sm-4 col-xs-2">
                            <a href="@Url.Action("Index","Persona")" class="btn btn-block btn-outline btn-default btn-volver  waves-effect waves-light">
                                <span class="visible-lg visible-md"><i class="icon-action-undo m-r-5 fa-1.5x"></i>Volver</span>
                                <span class="visible-xs visible-sm"><i class="icon-action-undo m-r-5 fa-1.5x"></i></span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    @{ Html.RenderPartial("_Editor.Oficina.Grid", Model); }
                </div>

            </div>
        </form>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function () {
        personaoficina.grid.load();
    });
</script>

SistemaComercial.App.SGC/SGC/Views/Persona/_Editor.cshtml
@using SistemaComercial.App.Utility
@using SGC.Helper
@model SGC.Models.Persona.PersonaEditorViewModel

@{
    ViewBag.Title = "Empresas";
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Mantenimiento Empresa</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20"><i class="ti-settings text-white"></i></button>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
            <li class="active">Empresas</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 white-box">

        <ul class="nav customtab nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#home1" aria-controls="home" role="tab" data-toggle="tab" aria-expanded="true"><span class="visible-xs"><i class="ti-home"></i></span><span class="hidden-xs"> Datos</span></a></li>
            <li role="presentation" class=""><a href="#profile1" aria-controls="profile" role="tab" data-toggle="tab" aria-expanded="false"><span class="visible-xs"><i class="ti-user"></i></span> <span class="hidden-xs">Oficinas</span></a></li>
            <li role="presentation" class=""><a href="#messages1" aria-controls="messages" role="tab" data-toggle="tab" aria-expanded="false"><span class="visible-xs"><i class="ti-email"></i></span> <span class="hidden-xs">Contactos</span></a></li>
        </ul>

        <!--PANELES-->

        <div class="tab-content">

            <div role="tabpanel" class="tab-pane fade active in" id="home1">

                <form id="personaEditorForm" enctype="multipart/form-data" method="POST" action="/" class="form-horizontal" autocomplete="off">

                    @Html.HiddenFor(model => model.Persona.iCodPer)
                    <input type="hidden" value="@Constantes.Tablas.TipoDocIdentidad.RUC" id="hdnTipDocIdeRuc" />
                    <input type="hidden" value="@Constantes.Tablas.TipoDocIdentidad.DNI" id="hdnTipDocIdeDni" />

                    <div class="panel panel-default">

                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-lg-2 col-sm-4 col-xs-2">
                                    <button class="btn btn-block btn-outline btn-default btn-agregar waves-effect waves-light">
                                        <span class="visible-lg visible-md"><i class="ti-save m-r-5 fa-1.5x"></i>Guardar</span>
                                        <span class="visible-xs visible-sm"><i class="ti-save m-r-5 fa-1.5x"></i></span>
                                    </button>
                                </div>
                                <div class="col-lg-2 col-sm-4 col-xs-2">
                                    <a href="@Url.Action("Search","Persona")" class="btn btn-block btn-outline btn-default btn-volver  waves-effect waves-light">
                                        <span class="visible-lg visible-md"><i class="icon-action-undo m-r-5 fa-1.5x"></i>Volver</span>
                                        <span class="visible-xs visible-sm"><i class="icon-action-undo m-r-5 fa-1.5x"></i></span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="panel-body">
                            <div class="form-group">

                                <div class="col-md-6">
                                    <label class="col-sm-6 control-label">Tipo de Documento :</label>
                                    <div class="col-sm-6">
                                        @Html.DropDownListFor(model => model.Persona.tiCodTipDocIde, Model.LstTipDocIdentidad, "--Seleccione--", new { @class = "form-control form-control-line", @required = "required" })
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <label class="col-sm-6 control-label">País :</label>
                                    <div class="col-sm-6">
                                        @Html.DropDownListFor(model => model.Persona.siCodPais, Model.LstPaises, "--Seleccione--", new { @class = "form-control form-control-line", @required = "required" })
                                    </div>
                                </div>

                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label">N° Documento :</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.Persona.vNroDocIde, new { @class = "form-control form-control-line", @placeholder = "RUC / DNI", @required = "required", @maxlength = "20" })
                                </div>
                            </div>

                            <div class="form-group div-razsoc">
                                <label class="col-sm-3 control-label">Razón Social :</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.Persona.vRazonSocial, new { @class = "form-control form-control-line", @placeholder = "Razón Social", @maxlength = "50" })
                                </div>
                            </div>

                            <div class="form-group div-razsoc">
                                <label class="col-sm-3 control-label">Nombre Comercial :</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.Persona.vNombreComercial, new { @class = "form-control form-control-line", @placeholder = "Dirección de domicilio fiscal", @required = "required", @maxlength = "100" })
                                </div>
                            </div>

                            <div class="form-group div-name">
                                <label class="col-sm-3 control-label">Nombre :</label>
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.Persona.vNombres, new { @class = "form-control form-control-line", @placeholder = "Nombres", @maxlength = "20" })
                                </div>
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.Persona.vApPaterno, new { @class = "form-control form-control-line", @placeholder = "Ap. Paterno", @maxlength = "20" })
                                </div>
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.Persona.vApMaterno, new { @class = "form-control form-control-line", @placeholder = "Ap. Materno", @maxlength = "20" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label">Teléfonos :</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.Persona.vNumero, new { @class = "form-control form-control-line", @placeholder = "Teléfonos de empresa", @maxlength = "30" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label lbl-pagweb">Página Web :</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.Persona.vPaginaWeb, new { @class = "form-control form-control-line minu", @placeholder = "Página web", @maxlength = "40" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 control-label lbl-fecnac">Aniversario :</label>
                                <div class="input-group date col-sm-9">
                                    <div class="input-group-addon">
                                        <i class="fa fa-clock-o"></i>
                                    </div>
                                    @Html.TextBoxFor(model => model.Persona.sdFecNac, new { @class = "form-control pull-right  form-control-line" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 col-md-offset-3">
                                    <div class="checkbox checkbox-info">
                                        <input id="Persona_bPartner" name="Persona.bPartner" type="checkbox" value="true" @HelperFunciones.CheckedSi(Model.Persona.bPartner)>
                                        <label for="Persona_bPartner"> Partners </label>
                                    </div>
                                </div>

                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="checkbox checkbox-info">
                                        <input id="Persona_bCliente" name="Persona.bCliente" type="checkbox" value="true" @HelperFunciones.CheckedSi(Model.Persona.bCliente)>
                                        <label for="Persona_bCliente"> Clientes </label>
                                    </div>
                                    <div class="checkbox checkbox-info">
                                        <input id="Persona_bProveedor" name="Persona.bProveedor" type="checkbox" value="true" @HelperFunciones.CheckedSi(Model.Persona.bProveedor)>
                                        <label for="Persona_bProveedor"> Proveedores </label>
                                    </div>
                                </div>

                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="checkbox checkbox-info">
                                        <input id="Persona_bExportador" name="Persona.bExportador" type="checkbox" value="true" @HelperFunciones.CheckedSi(Model.Persona.bExportador)>
                                        <label for="Persona_bExportador"> Exportadores </label>
                                    </div>
                                    <div class="checkbox checkbox-info">
                                        <input id="Persona_bDistribuidor" name="Persona.bDistribuidor" type="checkbox" value="true" @HelperFunciones.CheckedSi(Model.Persona.bDistribuidor)>
                                        <label for="Persona_bDistribuidor"> Distribuidores </label>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                </form>

            </div>

            <div role="tabpanel" class="tab-pane fade" id="profile1">

                @{ Html.RenderPartial("_Editor.Oficina", Model); }

            </div>

            <div role="tabpanel" class="tab-pane fade" id="messages1">

                @{ Html.RenderPartial("_Editor.Contacto", Model); }

            </div>

        </div>

    </div>
</div>


<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        persona.editor.load();
    });
</script>

SistemaComercial.App.SGC/SGC/Views/Persona/_Index.cshtml
@model SGC.Models.Persona.PersonaGridViewModel

<div class="col-sm-12">
    <form id="personaGridForm" action="/" class="form-horizontal" autocomplete="off">
        <div class="panel panel-default">
            @{ Html.RenderPartial("_Index.Head", Model); }
        </div>
    </form>
</div>

<div class="col-sm-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Lista de Empresas/Personas
        </div>
        @{ Html.RenderPartial("_Index.Grid", Model); }
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        persona.grid.load();
    });
</script>