SistemaComercial.App.SGC/SGC/Models/Reporte/ReporteAlmacenValorizadoViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;
using System.Data;

namespace SGC.Models.Reporte
{
    public class ReporteAlmacenValorizadoViewModel
    {
        public ReporteAlmacenValorizadoViewModel() { }

        public ReporteAlmacenValorizadoViewModel(ReporteAlmacenesValorizadoResumidoResponseDto response)
        {
            LstMarcas = new List<SelectListItem>();

            if (response.ListaMarcas != null) foreach (GenericoListaDto item in response.ListaMarcas) LstMarcas.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
        }

        public List<SelectListItem> LstMarcas { get; set; }
        public ReporteAlmacenesValorizadoResumidoFiltroDto Filtro { get; set; }
        public string Marca { get; set; }
        public string Articulo { get; set; }

        public static DataTable DTReporteAlmacenResumido(ReporteAlmacenesValorizadoResumidoResponseDto response)
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.Add("Almacen", typeof(string));
            dt.Columns.Add("Suma", typeof(decimal));

            var cont = 0;
            foreach (var item in response.ListaAlmacenesValorizados)
            {
                dt.Rows.Add(item.Almacen, item.Suma);
                cont++;
            }

            return dt;
        }

        public static DataTable DTReporteAlmacenDetallado(ReporteAlmacenesValorizadoResumidoResponseDto response)
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.Add("Almacen", typeof(string));
            dt.Columns.Add("CodigoOriginal", typeof(string));
            dt.Columns.Add("Articulo", typeof(string));
            dt.Columns.Add("Serie", typeof(string));
            dt.Columns.Add("Costo", typeof(decimal));

            var cont = 0;
            foreach (var item in response.ListaAlmacenesValorizadosDet)
            {
                dt.Rows.Add(item.Almacen, item.CodigoOriginal, item.Articulo, item.Serie, item.Costo);
                cont++;
            }

            return dt;
        }
    }
}

SistemaComercial.App.SGC/SGC/Models/Reporte/ReporteKardexViewModel.cs
using System.Collections.Generic;
using SGC.ServicioSistemaComercial;
using System.Web.Mvc;
using System.Data;
using System.Linq;

namespace SGC.Models.Reporte
{
    public class ReporteKardexViewModel
    {
        public ReporteKardexViewModel() { }

        public ReporteKardexViewModel(ReporteKardexResponseDto response)
        {
            LstMarcas = new List<SelectListItem>();
            LstEmpresas = new List<SelectListItem>();
            LstMeses = new List<SelectListItem>();
            LstAlmacenes = new List<SelectListItem>();

            Filtro = new ReporteKardexFiltroDto
            {
                Anio = (int)System.DateTime.Now.Year,
                IdMes = (int)System.DateTime.Now.Month,
            };

            if (response.ListaMarcas != null) foreach (GenericoListaDto item in response.ListaMarcas) LstMarcas.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaEmpresas != null) foreach (GenericoListaDto item in response.ListaEmpresas) LstEmpresas.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaMeses != null) foreach (GenericoListaDto item in response.ListaMeses) LstMeses.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });
            if (response.ListaAlmacenes != null) foreach (GenericoListaDto item in response.ListaAlmacenes) LstAlmacenes.Add(new SelectListItem { Value = item.Codigo, Text = item.Descripcion });

            Mes = LstMeses.Single(x => x.Value == Filtro.IdMes.ToString()).Text;
        }

        public List<SelectListItem> LstMarcas { get; set; }
        public List<SelectListItem> LstEmpresas { get; set; }
        public List<SelectListItem> LstMeses { get; set; }
        public List<SelectListItem> LstAlmacenes { get; set; }
        public ReporteKardexFiltroDto Filtro { get; set; }
        public string Marca { get; set; }
        public string Articulo { get; set; }
        public string Mes { get; set; }
        public string Almacen { get; set; }

        public static DataTable DTReporteKardex(ReporteKardexResponseDto response)
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.Add("TipoMov", typeof(string));
            dt.Columns.Add("TipoDoc", typeof(string));
            dt.Columns.Add("NumeroDoc", typeof(string));
            dt.Columns.Add("UnMed", typeof(string));
            dt.Columns.Add("Codigo", typeof(string));
            dt.Columns.Add("Fecha", typeof(string));
            dt.Columns.Add("Cantidad", typeof(int));
            dt.Columns.Add("Articulo", typeof(string));
            dt.Columns.Add("Empresa", typeof(string));

            var cont = 0;
            foreach (var item in response.ListaKardex)
            {
                dt.Rows.Add(item.TipoMov, item.TipoDoc, item.NumeroDoc, item.UnMed, item.Codigo, item.Fecha, item.Cantidad, item.Articulo, item.Empresa);
                cont++;
            }

            return dt;
        }
    }
}

SistemaComercial.App.SGC/SGC/Controllers/ReporteController.cs
using SGC.Models.Reporte;
using System.Web.Mvc;
using SGC.ServicioSistemaComercial;
using System.Threading.Tasks;
using System.ServiceModel;
using SGC.Helper;
using System.Web.UI.WebControls;
using System.Data;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace SGC.Controllers
{
    [Atributos.SessionExpireFilter]
    public class ReporteController : Controller
    {
        ServicioSistemaComercialClient _ServicioSistemaComercial = new ServicioSistemaComercialClient();

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        public async Task<ActionResult> AlmacenValorizado()
        {
            try
            {
                //Construimos el modelo
                var response = await _ServicioSistemaComercial.ObtenerIndexReporteAlmacenesValorizadosResumidoAsync();

                var model = new ReporteAlmacenValorizadoViewModel(response);

                //Retornamos vista con modelo
                return View(model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>16/01/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        public async Task<ActionResult> _AlmacenValorizadoRes(ReporteAlmacenValorizadoViewModel model)
        {
            try
            {
                var request = new ReporteAlmacenesValorizadosResumidoRequestDto
                {
                    Filtro = model.Filtro
                };

                var response = await _ServicioSistemaComercial.ListaReporteAlmacenesValorizadosResumidoAsync(request);
                var dt = ReporteAlmacenValorizadoViewModel.DTReporteAlmacenResumido(response);
                //string subtitulo = string.Format("Cuadro de Stopes Programados del año {0}", model.Filtro.Anio.ToString());
                return ExportarPDFAlmacenValorizado(dt, "ReporteAlmacenValorizadoRes", "ReporteAlmacenValorizadoRes", "");
            }
            catch
            {
                throw;
            }

        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>16/01/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        public async Task<ActionResult> _AlmacenValorizadoDet(ReporteAlmacenValorizadoViewModel model)
        {
            try
            {
                var request = new ReporteAlmacenesValorizadosResumidoRequestDto
                {
                    Filtro = model.Filtro
                };

                var response = await _ServicioSistemaComercial.ListaReporteAlmacenesValorizadosDetalladoAsync(request);
                var dt = ReporteAlmacenValorizadoViewModel.DTReporteAlmacenDetallado(response);
                //string subtitulo = string.Format("Cuadro de Stopes Programados del año {0}", model.Filtro.Anio.ToString());
                return ExportarPDFAlmacenValorizado(dt, "ReporteAlmacenValorizadoDet", "ReporteAlmacenValorizadoDet", "");
            }
            catch
            {
                throw;
            }

        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>16/01/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        public ActionResult ExportarPDFAlmacenValorizado(DataTable dt, string reporte,
            string nombre, string subtitulo)
        {
            try
            {
                ReportDocument rd = new ReportDocument();

                rd.Load(Path.Combine(Request.MapPath(Request.ApplicationPath) + @"\Reportes\Salida\" + reporte + ".rpt"));
                rd.SetDataSource(dt);
                //rd.DataDefinition.FormulaFields["pSubtitulo"].Text = "'" + subtitulo + "'";
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();

                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);

                return File(stream, "application/pdf");
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }

        #region KARDEX

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>05/02/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        [HttpGet]
        public async Task<ActionResult> Kardex()
        {
            try
            {
                //Construimos el modelo
                var response = await _ServicioSistemaComercial.ObtenerIndexReporteKardexAsync();

                var model = new ReporteKardexViewModel(response);

                //Retornamos vista con modelo
                return View(model);
            }
            catch (FaultException<ServiceErrorResponseType> ex)
            {
                //Como existe excepción de lógica de negocio, lo enviamos al Vehiculo para ser procesado por este
                return Json(HelperJson.ConstruirJson(EnumTipoNotificacion.Advertencia, ex.Detail.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>16/01/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        public async Task<ActionResult> _Kardex(ReporteKardexViewModel model)
        {
            try
            {
                var request = new ReporteKardexRequestDto
                {
                    Filtro = model.Filtro
                };

                var response = await _ServicioSistemaComercial.ListaReporteKardexAsync(request);
                var dt = ReporteKardexViewModel.DTReporteKardex(response);
                //string subtitulo = string.Format("Cuadro de Stopes Programados del año {0}", model.Filtro.Anio.ToString());
                return ExportarPDFKardex(dt, "ReporteKardex", "ReporteKardex", model);
            }
            catch
            {
                throw;
            }

        }

        /// <summary>Método que devuelve el modelo para la vista de la grilla</summary>
        /// <param name="model">Modelo del request</param>
        /// <returns>Modelo para la vista de al grilla</returns>
        /// <remarks><list type="bullet">
        /// <item><CreadoPor>Bryan Luna Vásquez</CreadoPor></item>
        /// <item><FecCrea>16/01/2018</FecCrea></item>
        /// </list>
        /// <list type="bullet" >
        /// <item><FecActu>XXXX</FecActu></item>
        /// <item><Resp>XXXX</Resp></item>
        /// <item><Mot>XXXX</Mot></item></list></remarks>
        public ActionResult ExportarPDFKardex(DataTable dt, string reporte,
            string nombre, ReporteKardexViewModel model)
        {
            try
            {
                ReportDocument rd = new ReportDocument();

                rd.Load(Path.Combine(Request.MapPath(Request.ApplicationPath) + @"\Reportes\Salida\" + reporte + ".rpt"));
                rd.SetDataSource(dt);

SistemaComercial.App.SGC/SGC/Views/Reporte/AlmacenValorizado.cshtml
@model SGC.Models.Reporte.ReporteAlmacenValorizadoViewModel
@{
    ViewBag.Title = "Almacenes Valorizados";
}

<div class="row bg-title">
    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
        <h4 class="page-title">Reporte almacenes valorizados</h4>
    </div>
    <div class="col-lg-5 col-sm-5 col-md-5 col-xs-12 pull-right">
        <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20"><i class="ti-settings text-white"></i></button>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
            <li class="active">Reporte almacenes valorizados</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">

        <form id="reporteAlmacenesValorizadosGridForm" action="/" class="form-horizontal" autocomplete="off">

            <div class="col-md-4">
                <div class="panel panel-default" style="min-height:350px">
                    <div class="panel-heading">
                        Filtros de Reporte
                    </div>

                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                            <div class="form-group">
                                <label class="col-md-12">Marca</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(model => model.Filtro.CodigoMarca, Model.LstMarcas, "--Seleccione--", new { @class = "form-control form-control-line" })
                                    @Html.HiddenFor(model => model.Marca)
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-12">Producto</label>
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.Articulo, new { @class = "form-control form-control-line", @required = "required", @maxlength = "100" })
                                    @Html.HiddenFor(model => model.Filtro.CodigoArticulo)
                                </div>
                            </div>  
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="panel panel-default" style="min-height:350px">
                    <div class="panel-heading">
                        Tipo de Reporte
                    </div>

                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                            <div class="form-group">
                                <div class="radio radio-info">
                                    <input type="radio" checked="checked" name="treporte" id="radio1" value="@Url.Action("_AlmacenValorizadoRes", "Reporte", null)">
                                    <label for="radio1"> Resumido </label>
                                </div>
                                <div class="radio radio-info">
                                    <input type="radio" name="treporte" id="radio2" value="@Url.Action("_AlmacenValorizadoDet", "Reporte", null)">
                                    <label for="radio2"> Detallado </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <button type="button" onclick="reportealmacenesvalorizado.grid.visualizar()" class="btn btn-block btn-outline btn-default btn-agregar waves-effect waves-light">
                                        <span class="visible-lg visible-md"><i class="icon-plus m-r-5 fa-1.5x"></i>Visualizar</span>
                                        <span class="visible-xs visible-sm"><i class="icon-plus m-r-5 fa-1.5x"></i></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>




        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        reportealmacenesvalorizado.grid.load();
    });
</script>

SistemaComercial.App.SGC/SGC/Views/Reporte/Kardex.cshtml
@model SGC.Models.Reporte.ReporteKardexViewModel
@{
    ViewBag.Title = "Almacenes kardex";
}

<div class="row bg-title">
    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
        <h4 class="page-title">Reporte kardex</h4>
    </div>
    <div class="col-lg-5 col-sm-5 col-md-5 col-xs-12 pull-right">
        <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20"><i class="ti-settings text-white"></i></button>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
            <li class="active">Reporte kardex</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">

        <form id="reporteKardexGridForm" action="/" class="form-horizontal" autocomplete="off">

            <div class="col-md-4">
                <div class="panel panel-default" style="min-height:350px">
                    <div class="panel-heading">
                        Filtros de Reporte
                    </div>

                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">

                            <div class="form-group">
                                <label class="col-md-12">Almacén</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(model => model.Filtro.CodigoAlmacen, Model.LstAlmacenes, "--Seleccione--", new { @class = "form-control form-control-line" })
                                    @Html.HiddenFor(model => model.Almacen)
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-12">Año</label>
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.Filtro.Anio, new { @class = "form-control form-control-line", @required = "required", @maxlength = "100" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-12">Mes</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(model => model.Filtro.IdMes, Model.LstMeses, new { @class = "form-control form-control-line" })
                                    @Html.HiddenFor(model => model.Mes)
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-12">Empresa</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(model => model.Filtro.CodigoEmpresa, Model.LstEmpresas, "--Seleccione--", new { @class = "form-control form-control-line" })

                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-12">Marca</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(model => model.Filtro.CodigoMarca, Model.LstMarcas, "--Seleccione--", new { @class = "form-control form-control-line" })
                                    @Html.HiddenFor(model => model.Marca)
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-12">Producto</label>
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.Articulo, new { @class = "form-control form-control-line", @required = "required", @maxlength = "100" })
                                    @Html.HiddenFor(model => model.Filtro.CodigoProducto)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="panel panel-default" style="min-height:350px">
                    <div class="panel-heading">
                        Tipo de Reporte
                    </div>

                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                            <div class="form-group">
                                <div class="radio radio-info">
                                    <input type="radio" checked="checked" name="treporte" id="radio1" value="@Url.Action("_Kardex", "Reporte", null)">
                                    <label for="radio1"> Resumido </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <button type="button" onclick="reportekardex.grid.visualizar()" class="btn btn-block btn-outline btn-default btn-agregar waves-effect waves-light">
                                        <span class="visible-lg visible-md"><i class="icon-plus m-r-5 fa-1.5x"></i>Visualizar</span>
                                        <span class="visible-xs visible-sm"><i class="icon-plus m-r-5 fa-1.5x"></i></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>




        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        reportekardex.grid.load();
    });
</script>